# Dependencies
markdown:         kramdown
#highlighter:      pygments
highlighter:       rouge
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            RainHu
#tagline:          'Life is simple'
description:      'Life is simple'
url:              https://github.com/rainhu
baseurl:          /

author:
  name:           'Rain Hu'
  url:            https://github.com/rainhu
  email:          zhengyu_hu@163.com

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/rainhu
