# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            RainHu
tagline:          'A Jekyll theme'
description:      'To learn, to understand'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Rain Hu'
  url:            https://twitter.com/mdo
  email:          zhengyu_hu@163.com

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/rainhu
